Adv 423 data in demo app isn t working back end change
AdamikHQ/adamik-app pull request #70
Opened 2024-10-22 10:18 UTC by fabrice-adamik

JIRA:

2024-10-22 23:00 UTC, henri-ly commented on src/app/data/page.tsx
> +  };
This can be move outside of the component for more readibility

2024-10-22 23:01 UTC, henri-ly commented on src/app/data/page.tsx
> +  }, [transaction, selectedChain]);
same here

2024-10-22 23:02 UTC, henri-ly requested changes

2024-10-22 23:02 UTC, henri-ly commented on src/app/data/page.tsx
> +            {renderParsedData(transaction)}
U will want some loader here to have any feedback when we click button otherwise user will find it weird that nothing happened when he click the loop

2024-10-23 08:20 UTC, hakim-adamik commented on src/utils/types.ts
> +export type TokenInfo = {
Duplicate of existing `Token` type (in this file)

2024-10-23 09:12 UTC, henri-ly approved these changes

2024-10-23 09:14 UTC, henri-ly commented
<img width="550" alt="Screenshot 2024-10-23 at 11 11 50" src="https://github.com/user-attachments/assets/a05e30b3-5eed-4474-b4f6-b9e37078f11f">

<img width="534" alt="Screenshot 2024-10-23 at 11 13 12" src="https://github.com/user-attachments/assets/9465c169-699f-4691-bcca-b3e36b0e054a">

Good but we can have some refine for smaller screen ! later

2024-10-23 12:00 UTC, merged